### ISSUE TITLE
RUG issue

### ISSUE THREAD

**Issue by robertvlasiu** [Leroymilo/FurnitureFramework#2]
Hi, I am trying to add a rug, it works but then I can't pick it up anymore. I can only place it. Also, it seems that the bottom left corner is a solid tile, I can't get through it.

```javascript
"ntay.id.rug": {
            "Display Name": "Test Rug",
            "Price": 500,
	    "Force Type": "rug",
            "Rotations": 1,
			"Collisions": {
                "Width": 0,
                "Height": 0
            },
            "Indoors": true,
            "Outdoors": true,
            "Source Image": "assets/rug.png",
            "Source Rect": {
                "X": 0,
                "Y": 0,
                "Width": 62,
                "Height": 31
            },
            "Shows in Shops": [
                "Carpenter"
            ],
			"Frame Count": 4,
			"Frame Duration": 1000,
			"Animation Offset": {"X": 63, "Y": 0}
        },
```

**Comment by Leroymilo** [comment]
I am currently implementing a proper way to make rugs and paintings with the Furniture Framework, so I am not surprised it did not work for you, I'll add rugs to the "do not use" list of the "Force Type" field.

**Comment by robertvlasiu** [comment]
Got it, thank you!!

**Comment by Leroymilo** [comment]
Rugs are supported in the latest version by using `"Placement Type": "Rug"`
