### ISSUE TITLE
RectVariant not working 

### ISSUE THREAD

**Issue by robertvlasiu** [Leroymilo/FurnitureFramework#3]
Hi,
one more issue, I even tried with the neko statue but the variant doesn't seem to be working. I only see a statue and it's name is exactly as the display name here. The {{ReactVariant}} doesn't get replaced by the values in the offset.

```javascript
      "ntay.test": {
			"Display Name": "{{RectVariant}} Cat Statue",

			"Rotations": 1,
			"Collisions": {"Width": 1, "Height": 1},

			"Placement Restriction": 2,

			"Source Image": "assets/neko_statues.png",
			"Source Rect": {"X": 0, "Y": 0, "Width": 16, "Height": 32},
			"Source Rect Offsets": {
				"White": {"X": 0, "Y": 0},
				"Black": {"X": 0, "Y": 32}
			},

			"Shows in Shops": ["Carpenter"],

			"Frame Count": 7,
			"Frame Duration": 500,
			"Animation Offset": {"X": 16, "Y": 0}
		}
```

**Comment by Leroymilo** [comment]
Are you sure you're using the latest version of the Furniture Framework (2.0.0)? This is the Example Pack example and it works perfectly fine for me.
Also you wrote `{{ReactVariant}}` in your message while the code (and the correct token) is `{{RectVariant}}`, are you sure that you wrote it correctly in your content.json?

**Comment by robertvlasiu** [comment]
I was on 1.3.4, thank you!
